allowBuilds:
  esbuild: false
  sharp: false
  workerd: false
minimumReleaseAgeExclude:
  - '@astrojs/cloudflare@14.2.1'
  - '@astrojs/underscore-redirects@1.0.4'
  - miniflare@5.20260804.1-alpha
  - wrangler@4.121.0
